"""
配置文件 - 包含翻译字典、主题样式等常量
"""

# 多语言翻译字典
TRANSLATIONS = {
    "zh-CN": {  # 简体中文
        "app_title": "跨文化智能翻译助手 - 桌面版",
        "ui_language": "界面语言:",
        "source_lang": "源语言:",
        "target_lang": "目标语言:",
        "scenario": "场景:",
        "tone": "语气:",
        "lang_chinese": "中文",
        "lang_english": "英文",
        "lang_japanese": "日文",
        "scenario_tourism": "旅游/问路/生活",
        "scenario_dining": "餐桌聊天/饮食",
        "scenario_casual": "日常闲聊",
        "scenario_business": "商务/半正式",
        "tone_casual": "随和",
        "tone_neutral": "中性",
        "tone_polite": "正式/礼貌",
        "translation_settings": "翻译设置",
        "input_text": "输入文本",
        "input_placeholder": "请输入要翻译的内容...",
        "voice_start": "🎤 开始识别",
        "voice_stop": "⏹️ 停止识别",
        "clear": "🗑️ 清空",
        "translate_btn": "🌐 翻译并给出文化建议",
        "vosk_tip": "💡 提示: 首次使用需要下载免费的 Vosk 语音模型\n   访问: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 直译",
        "tab_natural": "💬 自然表达",
        "tab_advice": "🌏 文化建议",
        "play_audio": "🔊 朗读",
        "play_tooltip": "朗读此表达",
        "warning": "警告",
        "input_required": "请输入要翻译的内容。",
        "translating": "正在生成翻译和文化建议...",
        "translation_complete": "翻译完成！",
        "translation_failed": "翻译失败",
        "translation_error": "翻译错误",
        "translation_error_msg": "翻译过程中发生错误:\n",
        "voice_input_title": "语音输入",
        "voice_recognizing": "✅ 语音识别完成",
        "voice_failed": "语音输入失败",
        "tts_error": "TTS 错误",
        "basic_features": "基础功能",
        "theme_label": "主题:",
        "theme_light": "☀️ 浅色",
        "theme_dark": "🌙 深色",
    },
    "zh-TW": {  # 繁体中文
        "app_title": "跨文化智能翻譯助手 - 桌面版",
        "ui_language": "介面語言:",
        "source_lang": "源語言:",
        "target_lang": "目標語言:",
        "scenario": "場景:",
        "tone": "語氣:",
        "lang_chinese": "中文",
        "lang_english": "英文",
        "lang_japanese": "日文",
        "scenario_tourism": "旅遊/問路/生活",
        "scenario_dining": "餐桌聊天/飲食",
        "scenario_casual": "日常閒聊",
        "scenario_business": "商務/半正式",
        "tone_casual": "隨和",
        "tone_neutral": "中性",
        "tone_polite": "正式/禮貌",
        "translation_settings": "翻譯設置",
        "input_text": "輸入文本",
        "input_placeholder": "請輸入要翻譯的內容...",
        "voice_start": "🎤 開始識別",
        "voice_stop": "⏹️ 停止識別",
        "clear": "🗑️ 清空",
        "translate_btn": "🌐 翻譯並給出文化建議",
        "vosk_tip": "💡 提示: 首次使用需要下載免費的 Vosk 語音模型\n   訪問: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 直譯",
        "tab_natural": "💬 自然表達",
        "tab_advice": "🌏 文化建議",
        "play_audio": "🔊 朗讀",
        "play_tooltip": "朗讀此表達",
        "warning": "警告",
        "input_required": "請輸入要翻譯的內容。",
        "translating": "正在生成翻譯和文化建議...",
        "translation_complete": "翻譯完成！",
        "translation_failed": "翻譯失敗",
        "translation_error": "翻譯錯誤",
        "translation_error_msg": "翻譯過程中發生錯誤:\n",
        "voice_input_title": "語音輸入",
        "voice_recognizing": "✅ 語音識別完成",
        "voice_failed": "語音輸入失敗",
        "tts_error": "TTS 錯誤",
        "basic_features": "基礎功能",
        "theme_label": "主題:",
        "theme_light": "☀️ 淺色",
        "theme_dark": "🌙 深色",
    },
    "en": {  # English
        "app_title": "Cross-Cultural Translation Assistant - Desktop",
        "ui_language": "UI Language:",
        "source_lang": "Source:",
        "target_lang": "Target:",
        "scenario": "Scenario:",
        "tone": "Tone:",
        "lang_chinese": "Chinese",
        "lang_english": "English",
        "lang_japanese": "Japanese",
        "scenario_tourism": "Tourism/Daily Life",
        "scenario_dining": "Dining/Food",
        "scenario_casual": "Casual Chat",
        "scenario_business": "Business/Semi-formal",
        "tone_casual": "Casual",
        "tone_neutral": "Neutral",
        "tone_polite": "Polite/Formal",
        "translation_settings": "Translation Settings",
        "input_text": "Input Text",
        "input_placeholder": "Enter text to translate...",
        "voice_start": "🎤 Start Recording",
        "voice_stop": "⏹️ Stop Recording",
        "clear": "🗑️ Clear",
        "translate_btn": "🌐 Translate & Get Cultural Advice",
        "vosk_tip": "💡 Tip: First-time use requires downloading free Vosk speech models\n   Visit: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 Literal",
        "tab_natural": "💬 Natural",
        "tab_advice": "🌏 Cultural Advice",
        "play_audio": "🔊 Play",
        "play_tooltip": "Play this expression",
        "warning": "Warning",
        "input_required": "Please enter text to translate.",
        "translating": "Generating translation and cultural advice...",
        "translation_complete": "Translation complete!",
        "translation_failed": "Translation failed",
        "translation_error": "Translation Error",
        "translation_error_msg": "An error occurred during translation:\n",
        "voice_input_title": "Voice Input",
        "voice_recognizing": "✅ Voice recognition complete",
        "voice_failed": "Voice input failed",
        "tts_error": "TTS Error",
        "basic_features": "Basic Features",
        "theme_label": "Theme:",
        "theme_light": "☀️ Light",
        "theme_dark": "🌙 Dark",
    },
    "ja": {  # 日本語
        "app_title": "異文化翻訳アシスタント - デスクトップ版",
        "ui_language": "UI言語:",
        "source_lang": "元言語:",
        "target_lang": "対象言語:",
        "scenario": "シナリオ:",
        "tone": "トーン:",
        "lang_chinese": "中国語",
        "lang_english": "英語",
        "lang_japanese": "日本語",
        "scenario_tourism": "旅行/道案内/生活",
        "scenario_dining": "食事/会話",
        "scenario_casual": "日常会話",
        "scenario_business": "ビジネス/準公式",
        "tone_casual": "カジュアル",
        "tone_neutral": "ニュートラル",
        "tone_polite": "丁寧/フォーマル",
        "translation_settings": "翻訳設定",
        "input_text": "入力テキスト",
        "input_placeholder": "翻訳するテキストを入力してください...",
        "voice_start": "🎤 認識開始",
        "voice_stop": "⏹️ 認識停止",
        "clear": "🗑️ クリア",
        "translate_btn": "🌐 翻訳と文化的アドバイス",
        "vosk_tip": "💡 ヒント: 初回使用時は無料のVosk音声モデルをダウンロードする必要があります\n   訪問: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 直訳",
        "tab_natural": "💬 自然な表現",
        "tab_advice": "🌏 文化的アドバイス",
        "play_audio": "🔊 再生",
        "play_tooltip": "この表現を再生",
        "warning": "警告",
        "input_required": "翻訳するテキストを入力してください。",
        "translating": "翻訳と文化的アドバイスを生成中...",
        "translation_complete": "翻訳完了！",
        "translation_failed": "翻訳失敗",
        "translation_error": "翻訳エラー",
        "translation_error_msg": "翻訳中にエラーが発生しました:\n",
        "voice_input_title": "音声入力",
        "voice_recognizing": "✅ 音声認識完了",
        "voice_failed": "音声入力失敗",
        "tts_error": "TTS エラー",
        "basic_features": "基本機能",
        "theme_label": "テーマ:",
        "theme_light": "☀️ ライト",
        "theme_dark": "🌙 ダーク",
    },
    "es": {  # Español
        "app_title": "Asistente de Traducción Intercultural - Escritorio",
        "ui_language": "Idioma de UI:",
        "source_lang": "Origen:",
        "target_lang": "Destino:",
        "scenario": "Escenario:",
        "tone": "Tono:",
        "lang_chinese": "Chino",
        "lang_english": "Inglés",
        "lang_japanese": "Japonés",
        "scenario_tourism": "Turismo/Vida Diaria",
        "scenario_dining": "Comida/Gastronomía",
        "scenario_casual": "Charla Casual",
        "scenario_business": "Negocios/Semi-formal",
        "tone_casual": "Casual",
        "tone_neutral": "Neutral",
        "tone_polite": "Cortés/Formal",
        "translation_settings": "Configuración de Traducción",
        "input_text": "Texto de Entrada",
        "input_placeholder": "Ingrese el texto a traducir...",
        "voice_start": "🎤 Iniciar Grabación",
        "voice_stop": "⏹️ Detener Grabación",
        "clear": "🗑️ Limpiar",
        "translate_btn": "🌐 Traducir y Obtener Consejos Culturales",
        "vosk_tip": "💡 Consejo: El primer uso requiere descargar modelos de voz Vosk gratuitos\n   Visite: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 Literal",
        "tab_natural": "💬 Natural",
        "tab_advice": "🌏 Consejos Culturales",
        "play_audio": "🔊 Reproducir",
        "play_tooltip": "Reproducir esta expresión",
        "warning": "Advertencia",
        "input_required": "Por favor ingrese texto para traducir.",
        "translating": "Generando traducción y consejos culturales...",
        "translation_complete": "¡Traducción completa!",
        "translation_failed": "Traducción fallida",
        "translation_error": "Error de Traducción",
        "translation_error_msg": "Ocurrió un error durante la traducción:\n",
        "voice_input_title": "Entrada de Voz",
        "voice_recognizing": "✅ Reconocimiento de voz completo",
        "voice_failed": "Entrada de voz fallida",
        "tts_error": "Error TTS",
        "basic_features": "Funciones Básicas",
        "theme_label": "Tema:",
        "theme_light": "☀️ Claro",
        "theme_dark": "🌙 Oscuro",
    },
    "fr": {  # Français
        "app_title": "Assistant de Traduction Interculturelle - Bureau",
        "ui_language": "Langue UI:",
        "source_lang": "Source:",
        "target_lang": "Cible:",
        "scenario": "Scénario:",
        "tone": "Ton:",
        "lang_chinese": "Chinois",
        "lang_english": "Anglais",
        "lang_japanese": "Japonais",
        "scenario_tourism": "Tourisme/Vie Quotidienne",
        "scenario_dining": "Repas/Gastronomie",
        "scenario_casual": "Discussion Décontractée",
        "scenario_business": "Affaires/Semi-formel",
        "tone_casual": "Décontracté",
        "tone_neutral": "Neutre",
        "tone_polite": "Poli/Formel",
        "translation_settings": "Paramètres de Traduction",
        "input_text": "Texte d'Entrée",
        "input_placeholder": "Entrez le texte à traduire...",
        "voice_start": "🎤 Démarrer Enregistrement",
        "voice_stop": "⏹️ Arrêter Enregistrement",
        "clear": "🗑️ Effacer",
        "translate_btn": "🌐 Traduire et Obtenir des Conseils Culturels",
        "vosk_tip": "💡 Conseil: La première utilisation nécessite de télécharger des modèles vocaux Vosk gratuits\n   Visitez: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 Littéral",
        "tab_natural": "💬 Naturel",
        "tab_advice": "🌏 Conseils Culturels",
        "play_audio": "🔊 Lire",
        "play_tooltip": "Lire cette expression",
        "warning": "Avertissement",
        "input_required": "Veuillez entrer le texte à traduire.",
        "translating": "Génération de la traduction et des conseils culturels...",
        "translation_complete": "Traduction terminée!",
        "translation_failed": "Traduction échouée",
        "translation_error": "Erreur de Traduction",
        "translation_error_msg": "Une erreur s'est produite lors de la traduction:\n",
        "voice_input_title": "Entrée Vocale",
        "voice_recognizing": "✅ Reconnaissance vocale terminée",
        "voice_failed": "Entrée vocale échouée",
        "tts_error": "Erreur TTS",
        "basic_features": "Fonctions de Base",
        "theme_label": "Thème:",
        "theme_light": "☀️ Clair",
        "theme_dark": "🌙 Sombre",
    },
    "de": {  # Deutsch
        "app_title": "Interkultureller Übersetzungsassistent - Desktop",
        "ui_language": "UI-Sprache:",
        "source_lang": "Quelle:",
        "target_lang": "Ziel:",
        "scenario": "Szenario:",
        "tone": "Ton:",
        "lang_chinese": "Chinesisch",
        "lang_english": "Englisch",
        "lang_japanese": "Japanisch",
        "scenario_tourism": "Tourismus/Alltag",
        "scenario_dining": "Essen/Gastronomie",
        "scenario_casual": "Lockeres Gespräch",
        "scenario_business": "Geschäft/Halbformell",
        "tone_casual": "Locker",
        "tone_neutral": "Neutral",
        "tone_polite": "Höflich/Formell",
        "translation_settings": "Übersetzungseinstellungen",
        "input_text": "Eingabetext",
        "input_placeholder": "Geben Sie den zu übersetzenden Text ein...",
        "voice_start": "🎤 Aufnahme Starten",
        "voice_stop": "⏹️ Aufnahme Stoppen",
        "clear": "🗑️ Löschen",
        "translate_btn": "🌐 Übersetzen & Kulturelle Hinweise Erhalten",
        "vosk_tip": "💡 Tipp: Bei der ersten Verwendung müssen kostenlose Vosk-Sprachmodelle heruntergeladen werden\n   Besuchen Sie: https://alphacephei.com/vosk/models",
        "tab_literal": "📝 Wörtlich",
        "tab_natural": "💬 Natürlich",
        "tab_advice": "🌏 Kulturelle Hinweise",
        "play_audio": "🔊 Abspielen",
        "play_tooltip": "Diesen Ausdruck abspielen",
        "warning": "Warnung",
        "input_required": "Bitte geben Sie Text zum Übersetzen ein.",
        "translating": "Übersetzung und kulturelle Hinweise werden generiert...",
        "translation_complete": "Übersetzung abgeschlossen!",
        "translation_failed": "Übersetzung fehlgeschlagen",
        "translation_error": "Übersetzungsfehler",
        "translation_error_msg": "Während der Übersetzung ist ein Fehler aufgetreten:\n",
        "voice_input_title": "Spracheingabe",
        "voice_recognizing": "✅ Spracherkennung abgeschlossen",
        "voice_failed": "Spracheingabe fehlgeschlagen",
        "tts_error": "TTS-Fehler",
        "basic_features": "Grundfunktionen",
        "theme_label": "Design:",
        "theme_light": "☀️ Hell",
        "theme_dark": "🌙 Dunkel",
    },
}

# 主题样式表定义
THEME_STYLES = {
    "light": {
        "window_bg": "#f5f5f5",
        "widget_bg": "#ffffff",
        "text_color": "#333333",
        "secondary_text": "#666666",
        "border_color": "#e0e0e0",
        "accent_color": "#4CAF50",
        "hover_color": "#e8f5e9",
        "input_bg": "#ffffff",
        "button_bg": "#4CAF50",
        "button_hover": "#45a049",
        "button_disabled": "#cccccc",
    },
    "dark": {
        "window_bg": "#1e1e1e",
        "widget_bg": "#2d2d2d",
        "text_color": "#e0e0e0",
        "secondary_text": "#b0b0b0",
        "border_color": "#3d3d3d",
        "accent_color": "#66BB6A",
        "hover_color": "#3d3d3d",
        "input_bg": "#353535",
        "button_bg": "#66BB6A",
        "button_hover": "#5cb860",
        "button_disabled": "#4d4d4d",
    }
}

# Vosk 模型配置
VOSK_MODEL_MAP = {
    "zh": "models/zh",
    "en": "models/en",
    "ja": "models/ja"
}

# 语言名称映射
LANG_NAMES = {
    "zh": "中文",
    "en": "英文",
    "ja": "日文"
}

# 推荐模型信息
MODEL_INFO = {
    "zh": "vosk-model-small-cn-0.22 (约42MB)",
    "en": "vosk-model-small-en-us-0.15 (约40MB)",
    "ja": "vosk-model-small-ja-0.22 (约48MB)"
}
